server:
  port: 8080

spring:
  application:
    name: "Authentication"

  sql:
    init:
      mode: always

  devtools:
    add-properties: false

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapter:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:authentication_db}
    schema: "public"
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

jwt:
  secret-base64: ${JWT_SECRET_BASE64:VGhpcy1pcy1hLWRlZmF1bHQtc2VjcmV0LWtleS1iYXNlNjQ=}
  ttl-seconds: 3600