server:
  port: 8080

spring:
  application:
    name: "Authentication"
  # opcional si quieres inicializar scripts .sql al arrancar
  sql:
    init:
      mode: always

  devtools:
    add-properties: false

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapter:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "autenticacion_db"
    schema: "public"
    username: postgres
    password: postgres

jwt:
  secret-base64: ${JWT_SECRET_BASE64:VGhpcy1pcy1hLWRlZmF1bHQtc2VjcmV0LWtleS1iYXNlNjQ=}
  ttl-seconds: 3600